### ISSUE TITLE
remove context.go file

### ISSUE THREAD

**Issue by p0lyn0mial** [kcp-dev/logicalcluster#28]
We define two methods for writing/reading `logicalcluster.Name` to/from the `ctx` in `context.go` file. There seems to be at least 2 references to `logicalcluster.ClusterFromContext` method. 

The first reference is from `kcp-dev/apimachinery` repository, used by `NewClusterRoundTripper` which in turn is used by `SetMultiClusterRoundTripper`. 
Since we are no longer using a `RoundTripper` nor a `context` to store a logical cluster name it seems we could remove all of the above methods. Although `NewClusterRoundTripper` is also used in `controller-runtime` repository.

The second reference in from `controller-runtime` repository.

/assign @ncdc @stevekuznetsov

**Comment by sttts** [comment]
Fixed in https://github.com/kcp-dev/logicalcluster/pull/32
